(ServoControl Binary Method Example)
(For StepCraft D420 with UCCNC)
(Controls servo position using 4 binary outputs)

(Program setup)
G21         (Set units to mm)
G90         (Set absolute positioning)
G17         (Select XY plane)
G54         (Use work coordinate system 1)
G0 Z10      (Move Z to safe height)

(Initialize all outputs to 0 - servo at minimum position)
M63 P0      (Set output 0 LOW - LSB)
M63 P1      (Set output 1 LOW)
M63 P2      (Set output 2 LOW)
M63 P3      (Set output 3 LOW - MSB)

(Move to starting position)
G0 X10 Y10 F3000

(--- Example operation 1: Set servo to position 0 (binary 0000 = 0 degrees) ---)
(Outputs already initialized to 0000)
G1 Z-5 F500                 (Plunge into material)
G1 X50 Y10 F1000            (Cut along X axis)
G0 Z10                      (Retract Z)

(--- Example operation 2: Set servo to position 3 (binary 0011 = ~34 degrees) ---)
G0 X60 Y20                  (Move to new position)
M62 P0                      (Set output 0 HIGH - LSB)
M62 P1                      (Set output 1 HIGH)
M63 P2                      (Set output 2 LOW)
M63 P3                      (Set output 3 LOW - MSB)
G4 P0.5                     (Dwell for 0.5 seconds to allow servo to move)
G1 Z-5 F500                 (Plunge into material)
G1 X100 Y20 F1000           (Cut along X axis)
G0 Z10                      (Retract Z)

(--- Example operation 3: Set servo to position 5 (binary 0101 = ~57 degrees) ---)
G0 X60 Y40                  (Move to new position)
M62 P0                      (Set output 0 HIGH - LSB)
M63 P1                      (Set output 1 LOW)
M62 P2                      (Set output 2 HIGH)
M63 P3                      (Set output 3 LOW - MSB)
G4 P0.5                     (Dwell for 0.5 seconds to allow servo to move)
G1 Z-5 F500                 (Plunge into material)
G1 X100 Y40 F1000           (Cut along X axis)
G0 Z10                      (Retract Z)

(--- Example operation 4: Set servo to position 10 (binary 1010 = ~114 degrees) ---)
G0 X60 Y60                  (Move to new position)
M63 P0                      (Set output 0 LOW - LSB)
M62 P1                      (Set output 1 HIGH)
M63 P2                      (Set output 2 LOW)
M62 P3                      (Set output 3 HIGH - MSB)
G4 P0.5                     (Dwell for 0.5 seconds to allow servo to move)
G1 Z-5 F500                 (Plunge into material)
G1 X100 Y60 F1000           (Cut along X axis)
G0 Z10                      (Retract Z)

(--- Example operation 5: Set servo to position 15 (binary 1111 = ~180 degrees) ---)
G0 X60 Y80                  (Move to new position)
M62 P0                      (Set output 0 HIGH - LSB)
M62 P1                      (Set output 1 HIGH)
M62 P2                      (Set output 2 HIGH)
M62 P3                      (Set output 3 HIGH - MSB)
G4 P0.5                     (Dwell for 0.5 seconds to allow servo to move)
G1 Z-5 F500                 (Plunge into material)
G1 X100 Y80 F1000           (Cut along X axis)
G0 Z10                      (Retract Z)

(Return to home position and reset servo to position 0)
G0 X10 Y10                  (Return to home position)
M63 P0                      (Set output 0 LOW - LSB)
M63 P1                      (Set output 1 LOW)
M63 P2                      (Set output 2 LOW)
M63 P3                      (Set output 3 LOW - MSB)

(End program)
M30 